### ISSUE TITLE
Localhost refused to connect

### ISSUE THREAD

**Issue by N-kotecha** [human-nature-lab/breadboard-archive#1]
Hello,

I'm having trouble accessing the breadboard  v2.2.3 application on my windows computer. After using the script for the command prompt (listed in the FAQ), the application launches and I can access the local host. If I close the window or log out, I'm prompted with the following error. 

"This site can’t be reached

localhost refused to connect.
Search Google for localhost 9000
ERR_CONNECTION_REFUSED" 

I've tried changing the id via command prompt but it says the application is already running. It only works again after I uninstall and install again. But after that initial log-in, same error as above occurs. Any help would be appreciated! I think it's really cool and would love to use it for research purposes. 

Thanks,

Nikhil

**Comment by disperse** [comment]
A couple thoughts:

Make sure you're connecting to breadboard using http and not https.
It is possible that the logout link is (incorrectly) redirecting you to a https URL, let me know if this is the case.
