### ISSUE TITLE
Having trouble implementing an HTML form after coloring game is done.

### ISSUE THREAD

**Issue by jfngc** [human-nature-lab/breadboard-archive#10]
I'm trying to display a survey at the end of the coloring game and can not find any documentation or code snippets on how to implement an HTML form within breadboard. Attached is a screen shot of a similar survey form, except my survey form has 6 questions and no text area for comments. Any guidance you could provide would be very helpful. Thank you.
[formexample.docx](https://github.com/human-nature-lab/breadboard/files/1211924/formexample.docx)

**Comment by disperse** [comment]
Check out the ProposalStep in the Ultimatum game here:

https://github.com/human-nature-lab/breadboard-experiments/blob/master/UltimatumGame/Steps/ProposalStep.groovy
