### ISSUE TITLE
on installation, application-prod.conf must be modified if breadboard runs on separate machine from the one your browser runs on

### ISSUE THREAD

**Issue by carlmason** [human-nature-lab/breadboard-archive#12]
Suggestion for improving the documentation:

The admirably simple installation procedure for breadboard assumes that you are installing it on the same machine as runs your browser.  If, however, you install breadboard on a remote host then in order for it to run properly, it is necessary to modify application-prod.conf.   Specifically,  the lines:

```
# DEV http
breadboard.rootUrl="http://localhost:9000"
breadboard.wsUrl="ws://localhost:9000/connect"
```

Must be changed to to something like 

```
# DEV http
breadboard.rootUrl="http://192.168.x.x:9000"
breadboard.wsUrl="ws://192.168.x.x:9000/connect"
```

and then of course you browse to http://192.168.x.x:9000  (rather than to localhost).  IF you don't modify the applications-prod.conf in this way,  breadboard HALF WORKS.   You can create a user account and login,  but you can't create a new experiment and commands typed into the console are ignored.

**Comment by disperse** [comment]
You can find documentation about configuring breadboard on a server here:

[https://github.com/human-nature-lab/breadboard/wiki/Configuring-breadboard](https://github.com/human-nature-lab/breadboard/wiki/Configuring-breadboard)

Let us know if this documentation is unclear or if you need us to go into this process in more detail.

**Comment by carlmason** [comment]
Thanks --

The AMT directions look very good and,  happily that is my next step so I
appreciate that pointer.   What I am suggesting though is that the concise
directions that one encounters at breadboard.yale.edu:



are just a tiny bit  frustrating -- particularly for Linux users who are
likely to be installing on a remote server.  In that
case, these directions lead to some frustration because if you follow these
instructions, breadboard only half works.  And that in itself is not
obvious to someone who has never used it before.    A sentence at the
bottom noting that if you are installing it on a remote server another step
is required ... [link to AMT instructions]   would prevent hair loss.​

Thanks.

--Carl

**Comment by disperse** [comment]
Yes, I totally agree. I added a note to the simplified instructions on the website with a link to the full instructions on the wiki. 

P.S. If you're going to be running experiments on AMT before v2.3.0 is released you'll need a patch. Download it here: [http://breadboard.yale.edu/downloads/breadboard_2.10-v2.2.jar](http://breadboard.yale.edu/downloads/breadboard_2.10-v2.2.jar). Copy the downloaded Jar file into the breadboard/lib folder replacing the existing file. This fixes an issue that may prevent AMT workers from joining your experiment.
