### ISSUE TITLE
wiki example on `a.choose` does not work

### ISSUE THREAD

**Issue by mgagliol** [human-nature-lab/breadboard-archive#13]
The example proposed [here](https://github.com/human-nature-lab/breadboard/wiki/Language-Reference#actions):

```groovy   
def aiBehavior = { ai->
     // Sanity check to make sure the AI actually has choices to make
     if (ai.getProperty("choices")) {
        def choices = ai.getProperty("choices")
        // Choose a random choice
        def choice = choices[r.nextInt(choices.size())]
        a.choose(choice.uid)
     }
}
```

does not work. `a.choose` takes two parameters, the second being a structure containing choice parameters. As a workaround I use `a.choose(choice.uid, null)` instead.

**Comment by disperse** [comment]
Yes, you are correct. I will fix this in v2.3. If you want to apply this fix in advance of the v2.3 release, add the following method to `breadboard/groovy/hello.groovy` at line 905:

`def choose(String uid) {
  choose(uid, null)
}`
