### ISSUE TITLE
Execute single line of code

### ISSUE THREAD

**Issue by paulrconnor** [human-nature-lab/breadboard-archive#15]
At 3:59 in Tutorial 3 the narrator highlights the code 'g.empty()' and executes it via a keyboard shortcut. What is the shortcut to run a single line of code? If I highlight it and hit the 'execute' button it runs all the code in the script.

**Comment by disperse** [comment]
Highlight the code you want to run and then hit control + enter to execute just the highlighted part of the code.

Breadboard will only save the last executed code so, if you have a large amount of code saved in your script window, select one line and execute it, and then refresh your browser window, you will lose the rest of the script.

**Comment by JuKo007** [comment]
I´m running Breadboard v2.3.0 on Windows in Firefox and I´m also having issues with running a single line of code. If I highlight it and hit ctrl + enter, it still runs the whole script for me...

**Comment by disperse** [comment]
We were able to confirm this issue on Windows and Firefox. It works properly with Chrome. We'll address this issue in a future version of breadboard. Thanks.
