### ISSUE TITLE
Localhost 

### ISSUE THREAD

**Issue by djsabor** [human-nature-lab/breadboard-archive#2]
Hello -

I have installed the Java Development Kit 7 and the Breadboard package. When I attempt to launch, I get the following error:

`This site can’t be reached

localhost refused to connect.
Search Google for localhost 9000
ERR_CONNECTION_REFUSED`

Specs:
Mac OS X 10.11.9
Chrome Version 53.0.2785.101 (64-bit)

A colleague has also attempted to install in a similar situation (El Capitan; Chrome) and is having the same result. We are _not_ using https.

Thanks

**Comment by disperse** [comment]
Are there any errors in the terminal? When you launch breadboard the terminal should display:

```[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000```

If this is not displayed and there are error messages in the terminal, breadboard is not launching correctly.
