### ISSUE TITLE
private properties of edges

### ISSUE THREAD

**Issue by igelkotten90** [human-nature-lab/breadboard-archive#3]
Hello,

I have trouble setting a private property for edges.
Using the `e.private(v, key, value)` methods as documented in the wiki throws and error:

>  Caught error: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: groovy.lang.MissingMethodException.private() is applicable for argument types: () values: []

I think the method only expects two parameters, however, I cannot figure out which two. 

Thanks, 
Annika

**Comment by disperse** [comment]
This is an error in the documentation which I will correct.

There are two parameters, the first is the vertex of the player to whom the property should be visible, the second is a key value map.

### Example

Script dialog:
```groovy
g.E.each { edge->
  edge.private(edge.getVertex(Direction.IN), ["foo":"bar"])
}
```

Style:
```css
line[foo="bar"] {
  stroke: red;
}
```

This will show existing edges red for only half of the players.
