### ISSUE TITLE
Arrow markers for edges

### ISSUE THREAD

**Issue by igelkotten90** [human-nature-lab/breadboard-archive#4]
Hey,

I'm trying to add arrow markers to edges in the graph. 
I tried to utilize the markers already set up in the client-graph.js by using the css marker-end property.
However, no markers appear in the graph. 
```
line[arrow="1"] { 
  marker-end:"url(#end-green)";
}
```

**Comment by disperse** [comment]
There is a function to add arrows to edges in breadboard.

Add a property to the edge called 'arrow' with the ID of the vertex to point to (or 'both' to point to both) a comma, and then the color of the arrow (red/green by default).

By example:

```
g.addVertices(20)
g.random(0.4)
g.E.each { edge->
  edge.arrow = edge.getVertex(Direction.IN).id + ",green"
}
```

```
g.E.each { edge->
  edge.arrow = "both,red"
}
```
