### ISSUE TITLE
recording data

### ISSUE THREAD

**Issue by igelkotten90** [human-nature-lab/breadboard-archive#5]
Hey,

I've been running into some problems when trying to record experiment data. 
1) Parameters of an experiment always appear in the data window. However, additionally non-player action data recorded with a.addEvent(eventName, data) does not appear there. 
` a.addEvent("DropPlayer", ["pid": (player.id)])`
E.g. records nothing in the data, even when players are dropped. 

2) Sometimes the parameters recorded do not match with the names of the parameters. Either the columns are switched around or parameters from other, previously launched experiments is recorded.

3) How should the syntax look to record choices players make?  

Thank you in advance, 
I really appreciate all the support I'm getting here.

**Comment by disperse** [comment]
A couple things to check:

Make sure you've launched an experiment instance, not a test instance, by clicking the "Launch" button and not the "Test" button in the Launch dialog.

Make sure the a.addEvent action is being triggered correctly, for instance:

```groovy
a.setDropPlayerClosure({ player ->
  a.addEvent("DropPlayer", ["pid": (player.id)])
  player.text = c.get("Dropped")
  player.dropped = true
})
```

You can add an event property to player actions to automatically record player choices like so:

```groovy
g.V.each { player->
  a.add(player, {}, 
        [name: ("A"), 
         event: [name:"A", data:[pid:(player.id)]],
         result: {
           println("A")
         }],
        [name: ("B"), 
         event: [name:"B", data:[pid:(player.id)]],
         result: {
           println("B")
         }]) 
```

**Comment by igelkotten90** [comment]
Thank you for the answer. 
Unfortunately, I'm still not getting it to work. 
I am launching experiment instances, not tests and I am using the code to drop players that is provided in the example PublicGoods Game. Additionally, I tried to record the player choices in said public goods game. 
However, I cannot find any of the data anywhere once the game is over.

I'm running experiment instances of the example PublicGoods game after having changed the cooperation step to the following:
`cooperationStep = stepFactory.createStep()

cooperationStep.run = {
  println "cooperationStep.run"
  g.V.filter{it.active}.each { player->
    player.text = c.get("CooperationStep", coc, po)
   
    a.add(player, {},
      [name: "Cooperate", 
      event: [name:"A", data:[pid:player.id]], 
      result: {
      	player.private.cooperation = 1
      	player.neighbors.each { n->
        	player.private.score -= coc       
      	}
      player.text += "<p>Please wait for the other players to make their choices.</p>"
   	}],
      [name: "Defect", 
      event: [name:"B", data:[pid:player.id]],
      result: {
      	player.private.cooperation = -1
      	player.text += "<p>Please wait for the other players to make their choices.</p>"
    }])
  }
}
cooperationStep.done = {
  println "cooperationStep.done"
  resultsStep.start() 
}`
I did not make any other changes to the game.

**Comment by igelkotten90** [comment]
Thank you for the answer. 
Unfortunately, I'm still not getting it to work. 
I am launching experiment instances, not tests and I am using the code to drop players that is provided in the example PublicGoods Game. Additionally, I tried to record the player choices in said public goods game. 
However, I cannot find any of the data anywhere once the game is over.

I'm running experiment instances of the example PublicGoods game after having changed the player actions to the following:



    a.add(player, {},
      [name: "Cooperate", 
      event: [name:"A", data:[pid:player.id]], 
      result: {
      	player.private.cooperation = 1
      	player.neighbors.each { n->
        	player.private.score -= coc       
      	}
      player.text += "<p>Please wait for the other players to make their choices.</p>"
   	}],
      [name: "Defect", 
      event: [name:"B", data:[pid:player.id]],
      result: {
      	player.private.cooperation = -1
      	player.text += "<p>Please wait for the other players to make their choices.</p>"
    }])

I didn't make any other changes to the experiment.
