### ISSUE TITLE
Narrow down firewall rules

### ISSUE THREAD

**Issue by smith3863** [human-nature-lab/breadboard-archive#8]
We're trying to avoid leaving ports 9000 and 9443 open to the entire world. Can you explain what the ports are specifically used for so we can scope our firewall rules accordingly? 

If these are just used to serve up the web application, can they be remapped to ports 80/443?

I'm on the IT staff for the group running the project, not the actual developer. Forgive me if this was already mentioned elsewhere in the documentation.

**Comment by disperse** [comment]
9000 is for http and ws (websocket) and 9443 is for https and wss (secure websockets). You don't need both ports if your participants are only connecting using a secure or insecure URL.

As far as I know there is no way to use the lower port numbers which are reserved.

**Comment by pauldatta** [comment]
Your firewall ports can be mapped to application ports quite easily. You could therefore point 443 to 9000 and resolve SSL elsewhere.
