### ISSUE TITLE
Dropping idle players from the game

### ISSUE THREAD

**Issue by igelkotten90** [human-nature-lab/breadboard-archive#9]
When running breadboard on a server it seems that the the function to drop idle players miss-functions.
It seems to drop players around 1 sec before the  countdown has run out. If players click the required button to closely to the end of the timer they either get dropped anyway or they get "semi-dropped". I.e. the data log records them  as having  been dropped but they do not get the drop screen and the game does not move on for other players. But at the same time they are unable to further participate. 

Dropping them again manually from the game does not cause other players to get unstuck.

**Comment by disperse** [comment]
This is likely due to the player's clock being different than the server's clock. We're looking at better ways to handle timer synchronization for v2.4.
